backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    editor:
      preview: false
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "servicio"
    editor:
      preview: false
    label: "Servicios" # Used in the UI, ie.: "New Post"
    folder: "site/content/servicio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: nombre
    fields: # The fields each document in this collection have
      - {label: "Nombre", name: "nombre", widget: "string"}
      - {label: "Descripcion", name: "descripcion", widget: "markdown"}
      - {label: "Imagen", name: "imagen", widget: "image", required: false}
  - name: "pages"
    editor:
      preview: false
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Por qué - Título" , name: porque, widget: string}
          - {label: "Por qué - Explicación" , name: porqueExplicacion, widget: string}
          - {label: "Motivos", name: porqueMotivos, widget: list, fields: [
              {label: "Titulo", name: "titulo", widget: string},
              {label: "Imagen", name: "imagen", widget: "image"}
              ]
            }
          - {label: "Servicios - Título" , name: servicios, widget: string}
          - {label: "Servicios - Explicación" , name: serviciosExplicacion, widget: string}
          - {label: "Servicios", name: serviciosListado, widget: list, fields: [
              {label: "Titulo", name: "titulo", widget: string},
              {label: "Explicacion", name: "explicacion", widget: string}
              ]
            }
          - {label: "Cintilla - Título" , name: cintillaTitulo, widget: string}
          - {label: "Cintilla - Descripción" , name: cintillaDescripcion, widget: string}
          - {label: "Cintilla - Botón" , name: cintillaBotón, widget: string}
          - {label: "Sobre Tere - Título" , name: sobreTereTitulo, widget: string}
          - {label: "Sobre Tere - Subtítulo" , name: sobreTereSubtitulo, widget: string}
          - {label: "Sobre Tere - Descripción" , name: sobreTereDescripción, widget: string}
          - {label: "Sobre Tere - Botón" , name: sobreTereBoton, widget: string}
          - {label: "Testimonios - Título" , name: testimoniosTitulo, widget: string}
          - {label: "Testimonios - Subtítulo" , name: testimoniosSubtitulo, widget: string}
          - {label: "Testimonios", name: testimoniosListado, widget: list, fields: [
              {label: "Nombre", name: "nombre", widget: string},
              {label: "Titular", name: "titular", widget: string},
              {label: "Descripción", name: "descripcion", widget: string}
              ]
            }
